//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Task item</summary>
	[PublishedContentModel("taskItem")]
	public partial class TaskItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "taskItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TaskItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TaskItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Check Task Item
		///</summary>
		[ImplementPropertyType("checkTaskItem")]
		public bool CheckTaskItem
		{
			get { return this.GetPropertyValue<bool>("checkTaskItem"); }
		}

		///<summary>
		/// Description Task Item
		///</summary>
		[ImplementPropertyType("descriptionTaskItem")]
		public IHtmlString DescriptionTaskItem
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionTaskItem"); }
		}

		///<summary>
		/// Title Task Item
		///</summary>
		[ImplementPropertyType("titleTaskItem")]
		public string TitleTaskItem
		{
			get { return this.GetPropertyValue<string>("titleTaskItem"); }
		}
	}
}
